sudo: required
dist: trusty
language: node_js
node_js:
  - node # descargará la última versión de node
addons:
  chrome: stable
before_script:
  # - npm install
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - npm run transpile
script:
  - npm run test
after_success:
  - npm run coveralls